(() => {
'use strict';
const sb=window.MobileMechanicSupabase;
const DBKEY='mobile_mechanic_ai_approved_v7';
let busy=false;
function cache(){try{return JSON.parse(localStorage.getItem(DBKEY)||'{}');}catch{return {};}}
function ctx(){const c=cache(),sid=c.session?.shopId;return {sid,shop:sid?c.shops?.[sid]:null,role:c.session?.role};}
function money(cents){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(cents||0)/100);}
function toast(msg,type=''){document.querySelector('.ai-credit-toast')?.remove();const d=document.createElement('div');d.className=`toast ai-credit-toast ${type}`;d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),4800);}
async function call(body){if(!sb)throw new Error('AI billing service is not connected.');const {data,error}=await sb.functions.invoke('ai-credit-billing',{body});if(error)throw new Error(error.message||'AI billing request failed.');if(data?.error)throw new Error(data.error);return data;}
async function getBalance(){return call({action:'balance'});}
async function buy(amountCents){if(busy||!sb)return;busy=true;try{const data=await call({action:'checkout',amount_cents:amountCents,return_url:`${location.origin}/#billing`});if(!data?.url)throw new Error('Stripe did not return a checkout link.');location.href=data.url;}catch(err){toast(err.message||'Could not add AI balance.','bad');busy=false;}}
function billingSection(){const radio=document.querySelector('input[name="billingPlan"]');const button=document.querySelector('[data-stripe-checkout]');return button?.closest('section')||radio?.closest('section')||null;}
async function refresh(panel){try{const b=await getBalance();panel.querySelector('[data-ai-credit-balance]').textContent=money(b.balance_cents);const promo=b.trial_active?`Trial AI ${money(b.promotional_cents)}`:'Trial AI expired';panel.querySelector('[data-ai-credit-detail]').textContent=`${promo} • Purchased balance ${money(b.purchased_cents)}`;}catch(err){panel.querySelector('[data-ai-credit-detail]').textContent='AI balance is temporarily unavailable.';}}
function mount(){const {sid,role}=ctx();if(!sid||role!=='shop')return;const section=billingSection();if(!section||section.querySelector('[data-ai-credit-panel]'))return;const panel=document.createElement('div');panel.dataset.aiCreditPanel='1';panel.style.cssText='margin-top:14px;padding:14px;border:1px solid #5c2227;border-radius:12px;background:#11161c';panel.innerHTML=`<div style="display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap"><div><b>AI BALANCE</b><div class="section-note" data-ai-credit-detail>Your 60-day trial includes starter AI credit. Purchased credit does not start the monthly subscription.</div></div><div style="font-size:22px;font-weight:800" data-ai-credit-balance>—</div></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px"><button type="button" class="btn btn-soft" data-ai-credit="500">Add $5</button><button type="button" class="btn btn-soft" data-ai-credit="1000">Add $10</button><button type="button" class="btn btn-soft" data-ai-credit="2500">Add $25</button><button type="button" class="btn btn-soft" data-ai-credit="5000">Add $50</button></div><div class="section-note" style="margin-top:9px">AI credit is prepaid usage credit only. It does not shorten the trial, change the selected plan, or begin subscription billing.</div>`;section.appendChild(panel);refresh(panel);}
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-ai-credit]');if(!b)return;e.preventDefault();e.stopPropagation();buy(Number(b.dataset.aiCredit||0));},true);
new MutationObserver(()=>setTimeout(mount,0)).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(mount,80));setTimeout(mount,500);
})();