(() => {
'use strict';
const sb=window.MobileMechanicSupabase;
const DBKEY='mobile_mechanic_ai_approved_v7';
let state=null,mounting=false;
function read(){try{return JSON.parse(localStorage.getItem(DBKEY)||'{}');}catch{return {};}}
function context(){const db=read(),sid=db.session?.shopId,shop=sid?db.shops?.[sid]:null,job=shop?.jobs?.find(j=>String(j.id)===String(db.session?.activeJobId));return {db,sid,shop,job};}
function esc(v=''){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function money(v){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0));}
function toast(msg,type=''){document.querySelector('.next-estimate-toast')?.remove();const d=document.createElement('div');d.className=`toast next-estimate-toast ${type}`;d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),3000);}
function shopRate(){return Number(context().shop?.settings?.laborRate||75);}
function blank(){return {status:'draft',parts:[],labor:[],note:'Additional work estimate. Separate from the original invoice.'};}
async function load(job){
  if(!sb||!job?.id)return blank();
  const {data,error}=await sb.from('jobs').select('ai_workup').eq('id',job.id).maybeSingle();if(error)throw error;
  const wo=data?.ai_workup?.work_order||{};
  const n=structuredClone(wo.additional_estimate||wo.next_invoice||blank());
  n.parts=Array.isArray(n.parts)?n.parts:[];n.labor=Array.isArray(n.labor)?n.labor:[];
  const rate=shopRate();n.labor=n.labor.map(x=>({...x,hours:x.hours??null,rate:Number(x.rate||rate),amount:x.amount??null}));
  return n;
}
function recalc(item){const h=Number(item.hours),r=Number(item.rate||shopRate());item.amount=Number.isFinite(h)&&h>=0&&item.hours!==null&&item.hours!==''?Math.round(h*r*100)/100:null;}
function partsTotal(){return state.parts.reduce((s,x)=>s+(Number(x.amount)||0),0);}
function laborTotal(){return state.labor.reduce((s,x)=>s+(Number(x.amount)||0),0);}
function partLine(x,i){return `<div class="nxe-row nxe-part"><b>${esc(x.name)}</b><label><span>Part $</span><input type="number" min="0" step="0.01" value="${x.amount??''}" data-nxe-part-amount data-nxe-index="${i}"></label><button class="nxe-remove" type="button" data-nxe-remove data-nxe-type="parts" data-nxe-index="${i}">×</button></div>`;}
function laborLine(x,i){return `<div class="nxe-row nxe-labor"><b class="nxe-labor-name">${esc(x.name)}</b><label class="nxe-hours"><input type="number" min="0" step="0.1" placeholder="hrs" value="${x.hours??''}" data-nxe-hours data-nxe-index="${i}"><span>hr</span></label><button class="btn btn-soft nxe-dh" type="button" data-identifix-open-row data-nxe-index="${i}">Direct-Hit</button><button class="btn btn-primary nxe-addtime" type="button" data-identifix-add-row data-nxe-index="${i}">Add Time</button><button class="nxe-remove" type="button" data-nxe-remove data-nxe-type="labor" data-nxe-index="${i}">×</button></div>`;}
function group(title,type,items){return `<div class="nxe-group"><div class="nxe-head"><h4>${title}</h4><button class="btn btn-soft" type="button" data-nxe-add="${type}">+ Add ${type==='parts'?'Part':'Labor'}</button></div>${items.length?items.map((x,i)=>type==='parts'?partLine(x,i):laborLine(x,i)).join(''):`<div class="nxe-empty">Nothing added yet.</div>`}</div>`;}
function markup(){const pt=partsTotal(),lt=laborTotal();return `<section class="nxe" data-next-invoice><div class="nxe-title"><div><div class="eyebrow">ADDITIONAL WORK ESTIMATE</div><h3>Separate From Original Invoice</h3></div><span class="badge orange">Draft Estimate</span></div>${group('Parts — Additional Estimate','parts',state.parts)}${group('Labor — Additional Estimate','labor',state.labor)}<div class="nxe-summary"><div><span>Parts</span><strong>${money(pt)}</strong></div><div><span>Labor</span><strong>${money(lt)}</strong></div><div class="nxe-est-total"><span>Estimate Total</span><strong>${money(pt+lt)}</strong></div></div></section>`;}
function css(){if(document.getElementById('next-estimate-style'))return;const s=document.createElement('style');s.id='next-estimate-style';s.textContent=`
.nxe{border-top:2px solid #673036;margin-top:16px;padding-top:14px}.nxe-title,.nxe-head,.nxe-summary>div{display:flex;align-items:center;justify-content:space-between;gap:8px}.nxe-title h3{margin:2px 0 0;font-size:15px}.nxe-group{margin-top:11px}.nxe-head h4{margin:0;font-size:12px;text-transform:uppercase}.nxe-head .btn{padding:4px 8px!important;min-height:28px!important;font-size:11px!important}.nxe-row{display:grid;gap:7px;align-items:center;background:#0a0e13;border:1px solid #28313a;border-radius:8px;padding:8px;margin-top:6px}.nxe-part{grid-template-columns:minmax(0,1fr) 110px 24px}.nxe-part label span{display:block;font-size:9px;color:#8e99a5}.nxe-part input{width:100%;box-sizing:border-box;background:#111820;color:#fff;border:1px solid #39434d;border-radius:6px;padding:6px}.nxe-labor{grid-template-columns:minmax(0,1fr) 72px 74px 70px 22px}.nxe-labor-name{font-size:12px;min-width:0}.nxe-hours{display:flex;align-items:center;gap:4px}.nxe-hours input{width:50px;background:#111820;color:#fff;border:1px solid #39434d;border-radius:6px;padding:6px;text-align:right}.nxe-hours span{font-size:10px;color:#aeb6c0}.nxe-dh,.nxe-addtime{padding:5px 6px!important;min-height:28px!important;font-size:10px!important}.nxe-remove{border:0;background:transparent;color:#d7dce1;font-size:20px;line-height:1}.nxe-summary{margin-top:11px;background:#0a0e13;border:1px solid #39434d;border-radius:8px;padding:9px}.nxe-summary>div{font-size:11px;padding:3px 0}.nxe-est-total{border-top:1px solid #39434d;margin-top:5px;padding-top:8px!important;font-size:12px!important}.nxe-empty{font-size:11px;color:#8e99a5;padding:7px}
@media(max-width:700px){.nxe-labor{grid-template-columns:minmax(0,1fr) 66px 68px 66px 20px}.nxe-dh,.nxe-addtime{font-size:9px!important;padding:4px!important}.nxe-part{grid-template-columns:minmax(0,1fr) 96px 22px}}
`;document.head.appendChild(s);}
async function save(){const {sid,job}=context();if(!sb||!job?.id||!state)return;try{const {data,error}=await sb.from('jobs').select('ai_workup').eq('id',job.id).eq('shop_id',sid).single();if(error)throw error;const ai={...(data.ai_workup||{})},wo={...(ai.work_order||{})};wo.additional_estimate={...state,note:'Additional work estimate. Separate from original Square invoice #0738.',updated_at:new Date().toISOString()};delete wo.next_invoice;ai.work_order=wo;const r=await sb.from('jobs').update({ai_workup:ai,updated_at:new Date().toISOString()}).eq('id',job.id).eq('shop_id',sid);if(r.error)throw r.error;toast('Additional estimate updated.','good');}catch(e){toast(e.message||'Could not save estimate.','bad');}}
function rerender(){const el=document.querySelector('[data-next-invoice]');if(el)el.outerHTML=markup();}
function add(type){const name=(prompt(type==='parts'?'Part name:':'Labor operation:','')||'').trim();if(!name)return;if(type==='parts')state.parts.push({name,amount:null,status:'pending price'});else state.labor.push({name,hours:null,rate:shopRate(),amount:null,status:'pending time'});rerender();save();}
function bind(){document.addEventListener('change',e=>{const p=e.target.closest?.('[data-nxe-part-amount]');if(p&&state){const i=+p.dataset.nxeIndex;state.parts[i].amount=p.value===''?null:+p.value;save();rerender();return;}const h=e.target.closest?.('[data-nxe-hours]');if(h&&state){const i=+h.dataset.nxeIndex;state.labor[i].hours=h.value===''?null:+h.value;recalc(state.labor[i]);save();rerender();}},true);document.addEventListener('click',e=>{const a=e.target.closest?.('[data-nxe-add]');if(a){e.preventDefault();add(a.dataset.nxeAdd);return;}const r=e.target.closest?.('[data-nxe-remove]');if(r&&state){e.preventDefault();state[r.dataset.nxeType].splice(+r.dataset.nxeIndex,1);rerender();save();}},true);}
async function mount(){if(mounting||document.querySelector('[data-next-invoice]'))return;const {db,job}=context();if(db.session?.role!=='shop'||!job)return;const work=document.querySelector('[data-job-work-order]');if(!work)return;mounting=true;try{css();state=await load(job);work.insertAdjacentHTML('beforeend',markup());}finally{mounting=false;}}
bind();new MutationObserver(()=>setTimeout(mount,0)).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('hashchange',()=>{state=null;setTimeout(mount,150)});setTimeout(mount,1100);
})();