(() => {
'use strict';
const sb=window.MobileMechanicSupabase;
const DBKEY='mobile_mechanic_ai_approved_v7';
let state=null;
let mounting=false;

function read(){try{return JSON.parse(localStorage.getItem(DBKEY)||'{}');}catch{return {};}}
function context(){const db=read(),sid=db.session?.shopId,shop=sid?db.shops?.[sid]:null,job=shop?.jobs?.find(j=>String(j.id)===String(db.session?.activeJobId));return {db,shop,job};}
function esc(v=''){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));}
function money(v){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0));}
function toast(msg,type=''){document.querySelector('.next-estimate-toast')?.remove();const d=document.createElement('div');d.className=`toast next-estimate-toast ${type}`;d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),3000);}
function shopRate(){return Number(context().shop?.settings?.laborRate||75);}
function blank(){return {status:'draft',parts:[],labor:[],note:'Additional work estimate. This is separate from the original invoice.'};}

async function load(job){
  if(!sb||!job?.id)return blank();
  const {data,error}=await sb.from('jobs').select('ai_workup').eq('id',job.id).maybeSingle();
  if(error)throw error;
  const n=structuredClone(data?.ai_workup?.work_order?.next_invoice||blank());
  n.parts=Array.isArray(n.parts)?n.parts:[];
  n.labor=Array.isArray(n.labor)?n.labor:[];
  const rate=shopRate();
  n.labor=n.labor.map(x=>({...x,hours:x.hours??null,rate:Number(x.rate||rate),amount:x.amount??null}));
  n.note=String(n.note||'').replace(/next invoice/ig,'additional work estimate').replace(/invoice #0738 until finalized/ig,'original Square invoice #0738');
  return n;
}
function partsTotal(n){return n.parts.reduce((s,x)=>s+(Number.isFinite(Number(x.amount))?Number(x.amount):0),0);}
function laborTotal(n){return n.labor.reduce((s,x)=>s+(Number.isFinite(Number(x.amount))?Number(x.amount):0),0);}
function recalcLabor(item){const h=Number(item.hours),r=Number(item.rate);item.amount=Number.isFinite(h)&&h>=0&&Number.isFinite(r)&&r>=0&&item.hours!==null&&item.hours!==''?Math.round(h*r*100)/100:null;}
function partLine(item,index){const pending=item.amount===null||item.amount===undefined||item.amount==='';return `<div class="nxe-row nxe-part"><div class="nxe-main"><b>${esc(item.name)}</b>${item.note?`<small>${esc(item.note)}</small>`:''}</div><label><span>Part $</span><input type="number" step="0.01" min="0" placeholder="Price" value="${pending?'':esc(item.amount)}" data-nxe-part-amount data-nxe-index="${index}"></label><button type="button" class="nxe-remove" aria-label="Remove" data-nxe-remove data-nxe-type="parts" data-nxe-index="${index}">×</button></div>`;}
function laborLine(item,index){const amount=item.amount===null||item.amount===undefined||item.amount===''?null:Number(item.amount);return `<div class="nxe-row nxe-labor"><div class="nxe-main"><b>${esc(item.name)}</b>${item.note?`<small>${esc(item.note)}</small>`:''}</div><label><span>Hours</span><input type="number" step="0.25" min="0" placeholder="Hours" value="${item.hours===null||item.hours===undefined?'':esc(item.hours)}" data-nxe-hours data-nxe-index="${index}"></label><label><span>Rate</span><input type="number" step="0.01" min="0" value="${esc(item.rate||shopRate())}" data-nxe-rate data-nxe-index="${index}"></label><div class="nxe-line-total"><span>Labor</span><strong>${amount===null?'Pending':money(amount)}</strong></div><button type="button" class="nxe-remove" aria-label="Remove" data-nxe-remove data-nxe-type="labor" data-nxe-index="${index}">×</button></div>`;}
function partsGroup(items){return `<div class="nxe-group"><div class="nxe-head"><h4>Parts — Additional Estimate</h4><button class="btn btn-soft" type="button" data-nxe-add="parts">+ Add Part</button></div>${items.length?items.map((x,i)=>partLine(x,i)).join(''):'<div class="nxe-empty">No additional parts entered yet.</div>'}</div>`;}
function laborGroup(items){return `<div class="nxe-group"><div class="nxe-head"><h4>Labor — Additional Estimate</h4><button class="btn btn-soft" type="button" data-nxe-add="labor">+ Add Labor</button></div>${items.length?items.map((x,i)=>laborLine(x,i)).join(''):'<div class="nxe-empty">No additional labor entered yet.</div>'}</div>`;}
function markup(n){const pt=partsTotal(n),lt=laborTotal(n),total=pt+lt;const pendingParts=n.parts.some(x=>x.amount===null||x.amount===undefined||x.amount==='');const pendingLabor=n.labor.some(x=>x.amount===null||x.amount===undefined||x.amount===''||x.hours===null||x.hours===undefined||x.hours==='');return `<section class="nxe" data-next-invoice><div class="nxe-title"><div><div class="eyebrow">ADDITIONAL WORK ESTIMATE</div><h3>Separate From Original Invoice</h3></div><span class="badge orange">Draft Estimate</span></div>${partsGroup(n.parts)}${laborGroup(n.labor)}<div class="nxe-summary"><div><span>Parts subtotal</span><strong>${money(pt)}</strong></div><div><span>Labor subtotal</span><strong>${money(lt)}</strong></div><div class="nxe-est-total"><span>Additional Work Estimate Total</span><strong>${money(total)}</strong></div></div>${pendingParts||pendingLabor?'<div class="nxe-note">Some additional-work items are still waiting for a part price or labor hours.</div>':''}${n.note?`<div class="nxe-note">${esc(n.note)}</div>`:''}</section>`;}
function css(){if(document.getElementById('next-estimate-style'))return;const s=document.createElement('style');s.id='next-estimate-style';s.textContent=`
.nxe{border-top:2px solid #673036;margin-top:16px;padding-top:14px}.nxe-title,.nxe-head{display:flex;align-items:center;justify-content:space-between;gap:8px}.nxe-title h3{margin:2px 0 0;font-size:15px}.nxe-group{margin-top:11px}.nxe-head h4{margin:0;font-size:12px;text-transform:uppercase}.nxe-head .btn{padding:4px 8px!important;min-height:28px!important;font-size:11px!important}.nxe-row{display:grid;gap:7px;align-items:end;background:#0a0e13;border:1px solid #28313a;border-radius:8px;padding:8px;margin-top:6px}.nxe-part{grid-template-columns:minmax(0,1fr) 118px 28px}.nxe-labor{grid-template-columns:minmax(0,1fr) 86px 96px 92px 28px}.nxe-main{align-self:center}.nxe-main b{display:block;font-size:12px}.nxe-main small{display:block;font-size:10px;color:#8e99a5;margin-top:2px}.nxe-row label span,.nxe-line-total span{display:block;font-size:9px;color:#8e99a5;margin-bottom:3px}.nxe-row input{width:100%;box-sizing:border-box;background:#111820;color:#fff;border:1px solid #39434d;border-radius:6px;padding:6px}.nxe-line-total{align-self:center}.nxe-line-total strong{font-size:11px}.nxe-remove{border:0;background:transparent;color:#d7dce1;font-size:20px;line-height:1;align-self:center}.nxe-summary{margin-top:11px;background:#0a0e13;border:1px solid #39434d;border-radius:8px;padding:9px}.nxe-summary>div{display:flex;justify-content:space-between;gap:8px;font-size:11px;padding:3px 0}.nxe-est-total{border-top:1px solid #39434d;margin-top:5px;padding-top:8px!important;font-size:12px!important}.nxe-note{font-size:10px;color:#9da7b2;margin-top:6px}.nxe-empty{font-size:11px;color:#8e99a5;padding:7px}
@media(max-width:700px){.nxe-labor{grid-template-columns:minmax(0,1fr) 70px 82px 24px}.nxe-labor .nxe-line-total{grid-column:1 / span 3}.nxe-labor .nxe-remove{grid-column:4;grid-row:1 / span 2}.nxe-part{grid-template-columns:minmax(0,1fr) 102px 24px}}
`;document.head.appendChild(s);}
async function save(){
  const {job}=context();if(!sb||!job?.id||!state)return;
  try{const {data,error}=await sb.from('jobs').select('ai_workup').eq('id',job.id).single();if(error)throw error;const ai={...(data?.ai_workup||{})};ai.work_order={...(ai.work_order||{}),next_invoice:{...state,note:'Additional work estimate. Keep separate from the original Square invoice until customer authorization and final billing.',updated_at:new Date().toISOString()}};const r=await sb.from('jobs').update({ai_workup:ai,updated_at:new Date().toISOString()}).eq('id',job.id);if(r.error)throw r.error;toast('Additional work estimate updated.','good');}catch(err){toast(err?.message||'Could not save additional work estimate.','bad');}
}
function rerender(){const el=document.querySelector('[data-next-invoice]');if(el&&state)el.outerHTML=markup(state);}
function add(type){if(!state)return;const name=prompt(type==='parts'?'Part description:':'Labor description:');if(!name?.trim())return;if(type==='parts'){const raw=prompt('Part price (leave blank if not decided yet):','');const amount=raw?.trim()===''||raw===null?null:Number(raw);state.parts.push({name:name.trim(),amount:Number.isFinite(amount)?amount:null,status:'pending price'});}else{const hr=prompt('Labor hours (leave blank if not decided yet):','');const hours=hr?.trim()===''||hr===null?null:Number(hr);const item={name:name.trim(),hours:Number.isFinite(hours)?hours:null,rate:shopRate(),amount:null,status:'pending price'};recalcLabor(item);state.labor.push(item);}rerender();save();}
function bind(){
  document.addEventListener('change',e=>{const p=e.target.closest?.('[data-nxe-part-amount]');if(p&&state){const i=Number(p.dataset.nxeIndex);if(state.parts[i])state.parts[i].amount=p.value===''?null:Number(p.value);save();rerender();return;}const h=e.target.closest?.('[data-nxe-hours]');if(h&&state){const i=Number(h.dataset.nxeIndex);if(state.labor[i]){state.labor[i].hours=h.value===''?null:Number(h.value);recalcLabor(state.labor[i]);save();rerender();}return;}const r=e.target.closest?.('[data-nxe-rate]');if(r&&state){const i=Number(r.dataset.nxeIndex);if(state.labor[i]){state.labor[i].rate=r.value===''?shopRate():Number(r.value);recalcLabor(state.labor[i]);save();rerender();}}},true);
  document.addEventListener('click',e=>{const a=e.target.closest?.('[data-nxe-add]');if(a){e.preventDefault();add(a.dataset.nxeAdd);return;}const r=e.target.closest?.('[data-nxe-remove]');if(r&&state){e.preventDefault();const type=r.dataset.nxeType,index=Number(r.dataset.nxeIndex);state[type]?.splice(index,1);rerender();save();}},true);
}
async function mount(){if(mounting||document.querySelector('[data-next-invoice]'))return;const {db,job}=context();if(db.session?.role!=='shop'||!job)return;const work=document.querySelector('[data-job-work-order]');if(!work)return;mounting=true;try{css();state=await load(job);work.insertAdjacentHTML('beforeend',markup(state));}catch(err){console.error('additional estimate mount',err);}finally{mounting=false;}}
bind();new MutationObserver(()=>setTimeout(mount,0)).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('hashchange',()=>{state=null;setTimeout(mount,150);});setTimeout(mount,1100);
})();