(() => {
'use strict';
const sb=window.MobileMechanicSupabase;
const DBKEY='mobile_mechanic_ai_approved_v7';
let busy=false;
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function cache(){try{return JSON.parse(localStorage.getItem(DBKEY)||'{}');}catch{return {};}}
function context(){const c=cache(),sid=c.session?.shopId,shop=sid?c.shops?.[sid]:null,jobId=c.session?.activeJobId||null,job=shop?.jobs?.find?.(j=>j.id===jobId)||null;return {sid,shop,jobId,job};}
function vehicle(j){const v=j?.vehicle||{};return [v.year,v.make,v.model,v.trim,v.engine].filter(Boolean).join(' ');}
function toast(msg,type=''){document.querySelector('.tech-help-toast')?.remove();const d=document.createElement('div');d.className=`toast tech-help-toast ${type}`;d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),4500);}
function styles(){if(document.getElementById('techHelpStyles'))return;const s=document.createElement('style');s.id='techHelpStyles';s.textContent=`
.tech-help-fab{position:fixed;right:120px;bottom:calc(78px + env(safe-area-inset-bottom,0px));z-index:85;border:1px solid #384b62;background:linear-gradient(180deg,#182331,#101821);color:#fff;border-radius:999px;padding:10px 14px;display:flex;align-items:center;gap:7px;font-weight:850;box-shadow:0 12px 34px rgba(0,0,0,.42);cursor:pointer}.tech-help-fab:hover{border-color:#73a9dc}.tech-help-fab b{color:#8fc4f5}.tech-help-backdrop{position:fixed;inset:0;z-index:125;background:rgba(0,0,0,.74);display:grid;place-items:end center;padding:18px}.tech-help-modal{width:min(720px,100%);max-height:min(90vh,820px);overflow:auto;background:#0d1116;color:#f6f7f9;border:1px solid #365775;border-radius:14px;padding:16px;box-shadow:0 30px 90px rgba(0,0,0,.62)}.tech-help-modal h2{margin:0}.tech-help-modal .sub{color:#9da6b2;margin:5px 0 12px}.tech-help-job{background:#0a0e13;border:1px solid #293847;border-radius:9px;padding:10px;margin-bottom:10px}.tech-help-job b{display:block}.tech-help-modal textarea{width:100%;min-height:110px;background:#080b0f;color:#fff;border:1px solid #343c46;border-radius:9px;padding:11px;font:inherit;resize:vertical}.tech-help-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:10px}.tech-help-actions button{min-height:40px;border-radius:9px;padding:9px 13px;font-weight:850;cursor:pointer}.tech-help-close{background:#151a21;color:#fff;border:1px solid #343c46}.tech-help-send{background:#174e78;color:#fff;border:1px solid #3180b8}.tech-help-answer{margin-top:12px;background:#101820;border:1px solid #315a78;border-radius:10px;padding:13px;white-space:pre-wrap;line-height:1.5}.tech-help-answer-head{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:8px}.tech-help-answer-head button{background:#151a21;color:#fff;border:1px solid #3b4651;border-radius:7px;padding:6px 8px;cursor:pointer}.tech-help-note{font-size:10px;color:#7f8996;margin-top:8px}
@media(min-width:900px){.tech-help-fab{bottom:18px}}@media(max-width:460px){.tech-help-fab{right:auto;left:12px}.feedback-fab{right:12px}}
`;document.head.appendChild(s);}
function close(){document.querySelector('.tech-help-backdrop')?.remove();}
function open(){const {jobId,job}=context();if(!jobId)return toast('Open a job first so Technician Help has the vehicle context.','bad');close();const wrap=document.createElement('div');wrap.className='tech-help-backdrop';wrap.innerHTML=`<div class="tech-help-modal"><h2>Technician Help</h2><div class="sub">Ask Mobile Mechanic AI about the job you are working on.</div><div class="tech-help-job"><b>${esc(vehicle(job)||'Current vehicle')}</b><span>${esc(job?.complaint||'Current job context will be attached automatically.')}</span></div><form id="techHelpForm"><textarea name="question" maxlength="4000" required placeholder="What do you need help with? Example: I verified spark and fuel pressure. What should I test next for this rough idle?"></textarea><div class="tech-help-note">Vehicle, complaint, codes, findings, and previous tests are attached. Customer contact details are not sent.</div><div class="tech-help-actions"><button type="button" class="tech-help-close" data-tech-close>Close</button><button class="tech-help-send" type="submit">Ask Technician Help</button></div></form><div id="techHelpAnswer"></div></div>`;document.body.appendChild(wrap);wrap.addEventListener('click',e=>{if(e.target===wrap||e.target.closest('[data-tech-close]'))close();});wrap.querySelector('#techHelpForm').addEventListener('submit',ask);setTimeout(()=>wrap.querySelector('textarea')?.focus(),30);}
async function ask(e){e.preventDefault();if(busy)return;busy=true;const btn=e.currentTarget.querySelector('.tech-help-send'),box=document.getElementById('techHelpAnswer'),q=String(new FormData(e.currentTarget).get('question')||'').trim(),{jobId}=context();if(!q||!jobId){busy=false;return;}const old=btn.textContent;btn.disabled=true;btn.textContent='Thinking…';if(box)box.innerHTML='<div class="tech-help-answer">Reviewing the job context…</div>';try{if(!sb)throw new Error('Technician Help is not connected.');const {data,error}=await sb.functions.invoke('technician-help',{body:{job_id:jobId,question:q}});if(error)throw new Error(error.message||'Technician Help request failed.');if(data?.error)throw new Error(data.error);const answer=String(data?.answer||'').trim();if(!answer)throw new Error('No answer was returned.');if(box){box.innerHTML=`<div class="tech-help-answer"><div class="tech-help-answer-head"><b>Mobile Mechanic AI</b><button type="button" data-copy-answer>Copy</button></div>${esc(answer)}</div>`;box.querySelector('[data-copy-answer]').onclick=()=>navigator.clipboard?.writeText(answer).then(()=>toast('Answer copied.','good'));}e.currentTarget.querySelector('textarea').value='';}catch(err){if(box)box.innerHTML=`<div class="tech-help-answer">${esc(err.message||'Technician Help failed.')}</div>`;toast(err.message||'Technician Help failed.','bad');}finally{busy=false;btn.disabled=false;btn.textContent=old;}}
function install(){styles();const {sid,jobId}=context(),shell=document.querySelector('.shell');if(!shell||!sid||!jobId){document.querySelector('.tech-help-fab')?.remove();return;}if(document.querySelector('.tech-help-fab'))return;const b=document.createElement('button');b.type='button';b.className='tech-help-fab';b.innerHTML='<b>?</b><span>Tech Help</span>';b.setAttribute('aria-label','Ask Mobile Mechanic AI for technician help');b.onclick=open;document.body.appendChild(b);}
new MutationObserver(install).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(install,0));setTimeout(install,250);
})();