import { createClient } from "npm:@supabase/supabase-js@2.112.4";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
function envKey(jsonName:string,legacyName:string){try{const p=JSON.parse(Deno.env.get(jsonName)||"{}");if(p?.default)return p.default;}catch{}return Deno.env.get(legacyName)||"";}
function offlineAnswer(context:any,question:string){
  const vehicle=[context?.vehicle?.year,context?.vehicle?.make,context?.vehicle?.model,context?.vehicle?.engine].filter(Boolean).join(" ")||"this vehicle";
  return `Technician Help is using its built-in diagnostic mode while the AI provider account is unavailable.\n\nAssessment\nFor ${vehicle}, do not replace a component from the symptom alone. Use the complaint, codes, scan data, and tests already completed to isolate the system causing: ${question}\n\nNext tests\n1. Verify battery voltage, grounds, connectors, fuses, and scan-tool communication.\n2. Check all stored, pending, and history codes plus freeze-frame data.\n3. Compare commanded versus actual data for the system involved. For a low-power complaint, check fuel trims, MAF/MAP, throttle position, ignition timing, fuel pressure under load, exhaust restriction, and mechanical compression.\n4. Reproduce the symptom safely and record the measurement that changes when the fault occurs.\n5. Test the suspected circuit or component before replacing it.\n\nWhat would confirm it\nA failed measurement outside the manufacturer specification that follows the suspect circuit/component and returns to normal after correction.\n\nSafety / verification\nStop if the vehicle is unsafe to road-test. Verify exact specifications, wiring, torque values, and procedures in official service information.`;
}
function outputText(data:any){if(typeof data?.output_text==="string"&&data.output_text.trim())return data.output_text.trim();const out:string[]=[];for(const item of data?.output||[])for(const c of item?.content||[])if(c?.type==="output_text"&&c?.text)out.push(c.text);return out.join("\n").trim();}
async function creditState(admin:any,shopId:string,trialExpiresAt:any){const {data,error}=await admin.from("ai_credit_transactions").select("amount_cents,credit_bucket").eq("shop_id",shopId);if(error)throw error;let promotional=0,purchased=0;for(const r of data||[]){const n=Number(r.amount_cents||0);if(r.credit_bucket==="promotional")promotional+=n;else purchased+=n;}const end=trialExpiresAt?new Date(trialExpiresAt).getTime():0;const trialActive=Boolean(end&&Date.now()<end);if(!trialActive)promotional=0;return {promotional:Math.max(0,promotional),purchased,total:Math.max(0,promotional)+purchased};}
async function meterAI(admin:any,args:{shopId:string,userId:string|null,feature:string,model:string,response:any,trialExpiresAt:any,metadata?:any}){const responseId=String(args.response?.id||"");if(!responseId)return 0;const {data:existing}=await admin.from("ai_usage_ledger").select("id,billable_cost_cents").eq("openai_response_id",responseId).maybeSingle();if(existing)return Number(existing.billable_cost_cents||0);const {data:rate,error:rateError}=await admin.from("ai_model_rates").select("input_per_million,cached_input_per_million,output_per_million").eq("model",args.model).eq("active",true).maybeSingle();if(rateError||!rate)throw rateError||new Error(`AI rate not configured for ${args.model}.`);const u=args.response?.usage||{},input=Number(u.input_tokens||0),cached=Math.min(input,Number(u.input_tokens_details?.cached_tokens||0)),output=Number(u.output_tokens||0),nonCached=Math.max(0,input-cached);const cents=Number((((nonCached*Number(rate.input_per_million)+cached*Number(rate.cached_input_per_million)+output*Number(rate.output_per_million))/1_000_000)*100).toFixed(6));const state=await creditState(admin,args.shopId,args.trialExpiresAt);const promoDebit=Math.min(Math.max(0,cents),state.promotional),purchasedDebit=Math.max(0,cents-promoDebit);if(promoDebit>0){const {error}=await admin.from("ai_credit_transactions").insert({shop_id:args.shopId,kind:"usage",amount_cents:-promoDebit,source:args.feature,reference_id:`ai_usage:${responseId}:promo`,credit_bucket:"promotional",metadata:{model:args.model,...(args.metadata||{})}});if(error&&error.code!=="23505")throw error;}if(purchasedDebit>0){const {error}=await admin.from("ai_credit_transactions").insert({shop_id:args.shopId,kind:"usage",amount_cents:-purchasedDebit,source:args.feature,reference_id:`ai_usage:${responseId}:purchased`,credit_bucket:"purchased",metadata:{model:args.model,...(args.metadata||{})}});if(error&&error.code!=="23505")throw error;}const {error:ledgerError}=await admin.from("ai_usage_ledger").insert({shop_id:args.shopId,user_id:args.userId,feature:args.feature,model:args.model,input_tokens:input,cached_input_tokens:cached,output_tokens:output,provider_cost_cents:cents,billable_cost_cents:cents,openai_response_id:responseId,metadata:args.metadata||{}});if(ledgerError&&ledgerError.code!=="23505")throw ledgerError;return cents;}

Deno.serve(async(req)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
  if(req.method!=="POST")return json({error:"Method not allowed"},405);
  const openaiKey=Deno.env.get("OPENAI_API_KEY")||"";if(!openaiKey)return json({error:"Technician Help is ready but the OpenAI API key has not been added to Supabase Edge Function secrets yet."},503);
  try{
    const supabaseUrl=Deno.env.get("SUPABASE_URL")!;const publishable=envKey("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY");const secret=envKey("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");const auth=req.headers.get("Authorization")||"";const userClient=createClient(supabaseUrl,publishable,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const admin=createClient(supabaseUrl,secret,{auth:{persistSession:false}});
    const {data:{user},error:userError}=await userClient.auth.getUser();if(userError||!user)return json({error:"Authentication required."},401);
    const body=await req.json().catch(()=>({}));const jobId=String(body.job_id||""),question=String(body.question||"").trim();if(!jobId||question.length<2||question.length>4000)return json({error:"Enter a technician question and open a valid job."},400);
    const {data:membership}=await admin.from("shop_members").select("shop_id,role,status").eq("user_id",user.id).eq("status","active").limit(1).maybeSingle();if(!membership)return json({error:"No active shop membership found."},403);
    const {data:shop}=await admin.from("shops").select("shop_id,name,plan,trial_expires_at").eq("shop_id",membership.shop_id).single();
    const wallet=await creditState(admin,membership.shop_id,shop?.trial_expires_at);if(wallet.total<=0)return json({error:"AI balance is empty. Add AI Balance in Billing to keep using AI tools.",code:"ai_balance_empty"},402);
    const {data:job}=await admin.from("jobs").select("id,shop_id,vehicle_id,status,customer_states,findings,codes,ai_workup").eq("id",jobId).eq("shop_id",membership.shop_id).single();if(!job)return json({error:"That job is not available in your shop."},404);
    const {data:vehicle}=await admin.from("vehicles").select("year,make,model,submodel,engine,drivetrain,mileage").eq("id",job.vehicle_id).eq("shop_id",membership.shop_id).maybeSingle();
    const {data:findings}=await admin.from("technician_findings").select("finding_text,diagnostic_codes,measurements,created_at").eq("job_id",jobId).eq("shop_id",membership.shop_id).order("created_at",{ascending:false}).limit(8);
    const {data:history}=await admin.from("technician_help_sessions").select("question,answer,created_at").eq("job_id",jobId).eq("shop_id",membership.shop_id).eq("status","completed").order("created_at",{ascending:false}).limit(4);
    const context={vehicle:vehicle||{},complaint:job.customer_states||"",current_status:job.status||"",codes:job.codes||"",current_findings:job.findings||"",structured_findings:findings||[],prior_ai_workup:job.ai_workup||null};
    const previous=(history||[]).reverse().map((h:any)=>`Technician: ${h.question}\nMobile Mechanic AI: ${h.answer}`).join("\n\n");
    const prompt=`CURRENT JOB CONTEXT\n${JSON.stringify(context,null,2)}\n\n${previous?`RECENT HELP ON THIS SAME JOB\n${previous}\n\n`:""}TECHNICIAN QUESTION\n${question}`;
    const model=shop?.plan==="solo"?"gpt-5.6-terra":"gpt-5.6-sol";
    const instructions="You are Mobile Mechanic AI Technician Help, an experienced automotive diagnostic assistant supporting a trained technician. Use the supplied vehicle/job context. Give practical diagnostic reasoning and the next safest tests in a useful order. Clearly separate likely causes from confirmed facts. Never invent exact torque specs, refrigerant capacities, wiring pinouts, labor times, TSBs, recalls, or manufacturer procedures; when exact service data is required, tell the technician to verify an authoritative service source. Flag unsafe conditions and stop-work situations. Do not tell the technician to rely solely on AI. Keep the answer concise enough to use while working, with: Assessment, Next tests, What would confirm it, and Safety/verification notes when relevant.";
    const resp=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${openaiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model,reasoning:{effort:"medium"},instructions,input:prompt})});
    const data=await resp.json().catch(()=>({}));if(!resp.ok){const e=data?.error||{},msg=e?.message||`OpenAI request failed (${resp.status}).`,code=e?.code||e?.type||`http_${resp.status}`;if(["billing_not_active","insufficient_quota"].includes(code)){const answer=offlineAnswer(context,question);await admin.from("technician_help_sessions").insert({shop_id:membership.shop_id,job_id:jobId,user_id:user.id,question,context,answer,model:"built_in_diagnostic",status:"completed"});return json({answer,model:"built_in_diagnostic",fallback:true,provider_notice:"AI provider billing is unavailable."});}await admin.from("technician_help_sessions").insert({shop_id:membership.shop_id,job_id:jobId,user_id:user.id,question,context,model,status:"error",error_message:`${code}: ${msg}`});return json({error:msg,code},502);}
    const aiCostCents=await meterAI(admin,{shopId:membership.shop_id,userId:user.id,feature:"technician_help",model,response:data,trialExpiresAt:shop?.trial_expires_at,metadata:{job_id:jobId}});
    const answer=outputText(data);if(!answer)throw new Error("The AI response did not contain text.");
    await admin.from("technician_help_sessions").insert({shop_id:membership.shop_id,job_id:jobId,user_id:user.id,question,context,answer,model,status:"completed"});
    await admin.from("feature_usage_events").insert({shop_id:membership.shop_id,feature:"technician_help",metadata:{job_id:jobId,model,ai_cost_cents:aiCostCents}});
    const after=await creditState(admin,membership.shop_id,shop?.trial_expires_at);
    return json({answer,model,ai_cost_cents:aiCostCents,ai_balance_cents:after.total});
  }catch(err){console.error(err);return json({error:err instanceof Error?err.message:"Technician Help failed."},500);}
});