import { createClient } from "npm:@supabase/supabase-js@2.112.4";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
function envKey(jsonName:string,legacyName:string){try{const p=JSON.parse(Deno.env.get(jsonName)||"{}");if(p?.default)return p.default;}catch{}return Deno.env.get(legacyName)||"";}
const now=()=>new Date().toISOString();
const addSeconds=(s:number)=>new Date(Date.now()+Math.max(0,s)*1000).toISOString();
const safeText=(v:unknown,max=4000)=>String(v??"").slice(0,max);
function base64url(s:string){const bytes=new TextEncoder().encode(s);let bin="";for(const b of bytes)bin+=String.fromCharCode(b);return btoa(bin).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed"},405);
 const supabaseUrl=Deno.env.get("SUPABASE_URL")!;const anon=envKey("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY");const service=envKey("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");
 const auth=req.headers.get("Authorization")||"";const userClient=createClient(supabaseUrl,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const admin=createClient(supabaseUrl,service,{auth:{persistSession:false}});
 const {data:{user}}=await userClient.auth.getUser();if(!user)return json({error:"Authentication required."},401);
 const {data:member}=await admin.from("shop_members").select("shop_id,role,status").eq("user_id",user.id).eq("status","active").limit(1).maybeSingle();if(!member)return json({error:"Active shop membership required."},403);
 const body=await req.json().catch(()=>({}));const action=String(body.action||"");
 const ownerManager=["shop_owner","manager"].includes(member.role);
 async function integration(provider:string){const {data:r}=await admin.from("shop_integrations").select("*").eq("shop_id",member.shop_id).eq("provider",provider).maybeSingle();return r;}
 async function cred(provider:string){const {data:r}=await admin.from("shop_integration_credentials").select("*").eq("shop_id",member.shop_id).eq("provider",provider).maybeSingle();return r;}
 async function saveCred(provider:string,c:any){await admin.from("shop_integration_credentials").upsert({...c,shop_id:member.shop_id,provider,updated_at:now()},{onConflict:"shop_id,provider"});}
 async function mark(provider:string,patch:any={}){await admin.from("shop_integrations").upsert({shop_id:member.shop_id,provider,...patch,updated_at:now()},{onConflict:"shop_id,provider"});}
 async function refresh(provider:string){let c=await cred(provider);if(!c?.access_token)return c;const exp=c.token_expires_at?new Date(c.token_expires_at).getTime():0;if(!exp||exp>Date.now()+120000)return c;if(!c.refresh_token)return c;
  if(["google_calendar","gmail","google_drive"].includes(provider)){
   const id=Deno.env.get("GOOGLE_CLIENT_ID")||"",secret=Deno.env.get("GOOGLE_CLIENT_SECRET")||"";if(!id||!secret)return c;
   const f=new URLSearchParams({client_id:id,client_secret:secret,refresh_token:c.refresh_token,grant_type:"refresh_token"});const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:f});const t=await r.json();if(!r.ok||!t.access_token)throw new Error("Google account needs to be reconnected.");c={...c,access_token:t.access_token,token_expires_at:addSeconds(Number(t.expires_in||3600)),token_type:t.token_type||c.token_type};await saveCred(provider,c);return c;
  }
  if(["microsoft_calendar","microsoft_email","onedrive"].includes(provider)){
   const id=Deno.env.get("MICROSOFT_CLIENT_ID")||"",secret=Deno.env.get("MICROSOFT_CLIENT_SECRET")||"",tenant=Deno.env.get("MICROSOFT_TENANT_ID")||"common";if(!id||!secret)return c;
   const f=new URLSearchParams({client_id:id,client_secret:secret,refresh_token:c.refresh_token,grant_type:"refresh_token"});const r=await fetch(`https://login.microsoftonline.com/${encodeURIComponent(tenant)}/oauth2/v2.0/token`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:f});const t=await r.json();if(!r.ok||!t.access_token)throw new Error("Microsoft account needs to be reconnected.");c={...c,access_token:t.access_token,refresh_token:t.refresh_token||c.refresh_token,token_expires_at:addSeconds(Number(t.expires_in||3600)),token_type:t.token_type||c.token_type};await saveCred(provider,c);return c;
  }
  if(provider==="dropbox"){
   const id=Deno.env.get("DROPBOX_CLIENT_ID")||Deno.env.get("DROPBOX_APP_KEY")||"",secret=Deno.env.get("DROPBOX_CLIENT_SECRET")||Deno.env.get("DROPBOX_APP_SECRET")||"";if(!id||!secret)return c;
   const f=new URLSearchParams({grant_type:"refresh_token",refresh_token:c.refresh_token,client_id:id,client_secret:secret});const r=await fetch("https://api.dropboxapi.com/oauth2/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:f});const t=await r.json();if(!r.ok||!t.access_token)throw new Error("Dropbox needs to be reconnected.");c={...c,access_token:t.access_token,token_expires_at:t.expires_in?addSeconds(Number(t.expires_in)):null};await saveCred(provider,c);return c;
  }
  if(provider==="quickbooks"){
   const id=Deno.env.get("QUICKBOOKS_CLIENT_ID")||Deno.env.get("INTUIT_CLIENT_ID")||"",secret=Deno.env.get("QUICKBOOKS_CLIENT_SECRET")||Deno.env.get("INTUIT_CLIENT_SECRET")||"";if(!id||!secret)return c;
   const f=new URLSearchParams({grant_type:"refresh_token",refresh_token:c.refresh_token});const r=await fetch("https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer",{method:"POST",headers:{Authorization:`Basic ${btoa(`${id}:${secret}`)}`,"Content-Type":"application/x-www-form-urlencoded",Accept:"application/json"},body:f});const t=await r.json();if(!r.ok||!t.access_token)throw new Error("QuickBooks needs to be reconnected.");c={...c,access_token:t.access_token,refresh_token:t.refresh_token||c.refresh_token,token_expires_at:addSeconds(Number(t.expires_in||3600)),refresh_token_expires_at:t.x_refresh_token_expires_in?addSeconds(Number(t.x_refresh_token_expires_in)):c.refresh_token_expires_at};await saveCred(provider,c);return c;
  }
  if(provider==="xero"){
   const id=Deno.env.get("XERO_CLIENT_ID")||"",secret=Deno.env.get("XERO_CLIENT_SECRET")||"";if(!id||!secret)return c;
   const f=new URLSearchParams({grant_type:"refresh_token",refresh_token:c.refresh_token});const r=await fetch("https://identity.xero.com/connect/token",{method:"POST",headers:{Authorization:`Basic ${btoa(`${id}:${secret}`)}`,"Content-Type":"application/x-www-form-urlencoded",Accept:"application/json"},body:f});const t=await r.json();if(!r.ok||!t.access_token)throw new Error("Xero needs to be reconnected.");c={...c,access_token:t.access_token,refresh_token:t.refresh_token||c.refresh_token,token_expires_at:addSeconds(Number(t.expires_in||1800))};await saveCred(provider,c);return c;
  }
  return c;
 }
 async function requireConnected(provider:string){const i=await integration(provider);if(i?.status!=="connected"&&provider!=="vin_lookup")throw new Error(`${provider.replaceAll("_"," ")} is not connected.`);const c=await refresh(provider);if(!c?.access_token&&!["twilio","google_maps","zapier","vin_lookup"].includes(provider))throw new Error(`${provider.replaceAll("_"," ")} credentials are missing.`);return c;}
 async function mapping(provider:string,type:string,localId:string){const {data}=await admin.from("integration_entity_mappings").select("*").eq("shop_id",member.shop_id).eq("provider",provider).eq("entity_type",type).eq("local_id",localId).limit(1).maybeSingle();return data;}
 async function saveMapping(provider:string,type:string,localId:string,externalId:string,syncToken:string|null=null,metadata:any={}){const m=await mapping(provider,type,localId);if(m){await admin.from("integration_entity_mappings").update({external_id:externalId,external_sync_token:syncToken,metadata,last_synced_at:now(),updated_at:now()}).eq("id",m.id);}else{await admin.from("integration_entity_mappings").insert({shop_id:member.shop_id,provider,entity_type:type,local_id:localId,external_id:externalId,external_sync_token:syncToken,metadata,last_synced_at:now()});}}
 try{
  if(action==="google_calendar.create_event"){
   const c=await requireConnected("google_calendar");const jobId=String(body.job_id||"");const {data:j}=await admin.from("jobs").select("*,customers(name,phone,email),vehicles(year,make,model,vin)").eq("shop_id",member.shop_id).eq("id",jobId).single();if(!j)throw new Error("Job not found.");if(!j.scheduled_start_at||!j.scheduled_end_at)throw new Error("Schedule the job first.");const vehicle=[j.vehicles?.year,j.vehicles?.make,j.vehicles?.model].filter(Boolean).join(" ");const ev={summary:`${j.customers?.name||"Customer"} - ${vehicle||"Service Job"}`,description:[j.customer_states,j.schedule_notes].filter(Boolean).join("\n\n"),start:{dateTime:j.scheduled_start_at},end:{dateTime:j.scheduled_end_at},location:j.current_location?.raw||undefined};const r=await fetch("https://www.googleapis.com/calendar/v3/calendars/primary/events",{method:"POST",headers:{Authorization:`Bearer ${c.access_token}`,"Content-Type":"application/json"},body:JSON.stringify(ev)});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||"Google Calendar event failed.");await saveMapping("google_calendar","job",jobId,d.id,null,{htmlLink:d.htmlLink});await mark("google_calendar",{last_synced_at:now(),last_error:null});return json({ok:true,event_id:d.id,link:d.htmlLink});
  }
  if(action==="microsoft_calendar.create_event"){
   const c=await requireConnected("microsoft_calendar");const jobId=String(body.job_id||"");const {data:j}=await admin.from("jobs").select("*,customers(name),vehicles(year,make,model)").eq("shop_id",member.shop_id).eq("id",jobId).single();if(!j)throw new Error("Job not found.");if(!j.scheduled_start_at||!j.scheduled_end_at)throw new Error("Schedule the job first.");const vehicle=[j.vehicles?.year,j.vehicles?.make,j.vehicles?.model].filter(Boolean).join(" ");const ev={subject:`${j.customers?.name||"Customer"} - ${vehicle||"Service Job"}`,body:{contentType:"Text",content:[j.customer_states,j.schedule_notes].filter(Boolean).join("\n\n")},start:{dateTime:j.scheduled_start_at,timeZone:"UTC"},end:{dateTime:j.scheduled_end_at,timeZone:"UTC"},location:{displayName:j.current_location?.raw||""}};const r=await fetch("https://graph.microsoft.com/v1.0/me/events",{method:"POST",headers:{Authorization:`Bearer ${c.access_token}`,"Content-Type":"application/json"},body:JSON.stringify(ev)});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||"Outlook Calendar event failed.");await saveMapping("microsoft_calendar","job",jobId,d.id,null,{webLink:d.webLink});await mark("microsoft_calendar",{last_synced_at:now(),last_error:null});return json({ok:true,event_id:d.id,link:d.webLink});
  }
  if(action==="gmail.send"){
   const c=await requireConnected("gmail");const to=safeText(body.to,320),subject=safeText(body.subject,500),text=safeText(body.text,20000);if(!to||!text)throw new Error("Recipient and message are required.");const raw=`To: ${to}\r\nSubject: ${subject}\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=UTF-8\r\n\r\n${text}`;const r=await fetch("https://gmail.googleapis.com/gmail/v1/users/me/messages/send",{method:"POST",headers:{Authorization:`Bearer ${c.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({raw:base64url(raw)})});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||"Gmail send failed.");await mark("gmail",{last_synced_at:now(),last_error:null});return json({ok:true,message_id:d.id});
  }
  if(action==="microsoft_email.send"){
   const c=await requireConnected("microsoft_email");const to=safeText(body.to,320),subject=safeText(body.subject,500),text=safeText(body.text,20000);if(!to||!text)throw new Error("Recipient and message are required.");const r=await fetch("https://graph.microsoft.com/v1.0/me/sendMail",{method:"POST",headers:{Authorization:`Bearer ${c.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({message:{subject,body:{contentType:"Text",content:text},toRecipients:[{emailAddress:{address:to}}]},saveToSentItems:true})});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d?.error?.message||"Microsoft email send failed.");}await mark("microsoft_email",{last_synced_at:now(),last_error:null});return json({ok:true});
  }
  if(action==="twilio.send_sms"){
   if(!["shop_owner","manager","service_writer","technician"].includes(member.role))return json({error:"Not allowed."},403);const sid=Deno.env.get("TWILIO_ACCOUNT_SID")||"",token=Deno.env.get("TWILIO_AUTH_TOKEN")||"",from=Deno.env.get("TWILIO_FROM_NUMBER")||"",msid=Deno.env.get("TWILIO_MESSAGING_SERVICE_SID")||"";if(!sid||!token||(!from&&!msid))throw new Error("Twilio is not configured.");const to=safeText(body.to,32),text=safeText(body.text,1500);if(!to||!text)throw new Error("Phone number and message are required.");const f=new URLSearchParams({To:to,Body:text});if(msid)f.set("MessagingServiceSid",msid);else f.set("From",from);const r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${encodeURIComponent(sid)}/Messages.json`,{method:"POST",headers:{Authorization:`Basic ${btoa(`${sid}:${token}`)}`,"Content-Type":"application/x-www-form-urlencoded"},body:f});const d=await r.json();if(!r.ok)throw new Error(d?.message||"SMS send failed.");await mark("twilio",{status:"connected",display_name:"Twilio SMS",public_settings:{shared_platform_service:true},last_synced_at:now(),last_error:null});return json({ok:true,message_id:d.sid,status:d.status});
  }
  if(action==="google_drive.upload_text"){
   const c=await requireConnected("google_drive");const name=safeText(body.name||"Mobile-Mechanic-AI.txt",180).replace(/[\\/]/g,"-");const text=safeText(body.text,200000);const boundary=`mm_${crypto.randomUUID()}`;const multipart=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify({name})}\r\n--${boundary}\r\nContent-Type: text/plain; charset=UTF-8\r\n\r\n${text}\r\n--${boundary}--`;const r=await fetch("https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink",{method:"POST",headers:{Authorization:`Bearer ${c.access_token}`,"Content-Type":`multipart/related; boundary=${boundary}`},body:multipart});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||"Google Drive upload failed.");await mark("google_drive",{last_synced_at:now(),last_error:null});return json({ok:true,file:d});
  }
  if(action==="onedrive.upload_text"){
   const c=await requireConnected("onedrive");const name=safeText(body.name||"Mobile-Mechanic-AI.txt",180).replace(/[\\/:*?\"<>|]/g,"-");const text=safeText(body.text,200000);const path=encodeURIComponent(name).replace(/%2F/g,"/");const r=await fetch(`https://graph.microsoft.com/v1.0/me/drive/root:/Mobile Mechanic AI/${path}:/content`,{method:"PUT",headers:{Authorization:`Bearer ${c.access_token}`,"Content-Type":"text/plain; charset=UTF-8"},body:text});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||"OneDrive upload failed.");await mark("onedrive",{last_synced_at:now(),last_error:null});return json({ok:true,file:{id:d.id,name:d.name,webUrl:d.webUrl}});
  }
  if(action==="dropbox.upload_text"){
   const c=await requireConnected("dropbox");const name=safeText(body.name||"Mobile-Mechanic-AI.txt",180).replace(/[\\/]/g,"-");const text=safeText(body.text,200000);const r=await fetch("https://content.dropboxapi.com/2/files/upload",{method:"POST",headers:{Authorization:`Bearer ${c.access_token}`,"Dropbox-API-Arg":JSON.stringify({path:`/Mobile Mechanic AI/${name}`,mode:"add",autorename:true,mute:false}),"Content-Type":"application/octet-stream"},body:text});const d=await r.json();if(!r.ok)throw new Error(d?.error_summary||"Dropbox upload failed.");await mark("dropbox",{last_synced_at:now(),last_error:null});return json({ok:true,file:{id:d.id,name:d.name,path:d.path_display}});
  }
  if(action==="google_maps.route"){
   const key=Deno.env.get("GOOGLE_MAPS_API_KEY")||"";if(!key)throw new Error("Google Maps is not configured.");const origin=safeText(body.origin,500),destination=safeText(body.destination,500);if(!origin||!destination)throw new Error("Origin and destination are required.");const r=await fetch("https://routes.googleapis.com/directions/v2:computeRoutes",{method:"POST",headers:{"Content-Type":"application/json","X-Goog-Api-Key":key,"X-Goog-FieldMask":"routes.distanceMeters,routes.duration,routes.polyline.encodedPolyline"},body:JSON.stringify({origin:{address:origin},destination:{address:destination},travelMode:"DRIVE",routingPreference:"TRAFFIC_AWARE"})});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||"Route calculation failed.");await mark("google_maps",{status:"connected",display_name:"Google Maps",public_settings:{shared_platform_service:true},last_synced_at:now(),last_error:null});return json({ok:true,route:d.routes?.[0]||null});
  }
  if(action==="zapier.emit"){
   const url=Deno.env.get("ZAPIER_WEBHOOK_URL")||Deno.env.get("MAKE_WEBHOOK_URL")||"";if(!url)throw new Error("Zapier / Make webhook is not configured.");const event=safeText(body.event||"mobile_mechanic_event",120),payload=body.payload&&typeof body.payload==="object"?body.payload:{};const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event,shop_id:member.shop_id,occurred_at:now(),payload})});if(!r.ok)throw new Error("Automation webhook failed.");await mark("zapier",{status:"connected",display_name:url.includes("make.com")?"Make":"Zapier",public_settings:{shared_platform_service:true},last_synced_at:now(),last_error:null});return json({ok:true});
  }
  if(action==="quickbooks.sync_customer"){
   if(!ownerManager)return json({error:"Only a shop owner or manager can sync accounting."},403);const c=await requireConnected("quickbooks");const customerId=String(body.customer_id||"");const {data:cu}=await admin.from("customers").select("*").eq("shop_id",member.shop_id).eq("id",customerId).single();if(!cu)throw new Error("Customer not found.");const realm=c.credential_metadata?.realm_id;if(!realm)throw new Error("QuickBooks company is missing.");const env=(c.credential_metadata?.environment||Deno.env.get("QUICKBOOKS_ENVIRONMENT")||"sandbox")==="production"?"production":"sandbox";const api=env==="production"?"https://quickbooks.api.intuit.com":"https://sandbox-quickbooks.api.intuit.com";let m=await mapping("quickbooks","customer",customerId),payload:any={DisplayName:cu.name,PrimaryEmailAddr:cu.email?{Address:cu.email}:undefined,PrimaryPhone:cu.phone?{FreeFormNumber:cu.phone}:undefined,BillAddr:cu.address?{Line1:cu.address}:undefined};if(m?.external_id){const gr=await fetch(`${api}/v3/company/${encodeURIComponent(realm)}/customer/${encodeURIComponent(m.external_id)}?minorversion=75`,{headers:{Authorization:`Bearer ${c.access_token}`,Accept:"application/json"}});const gd=await gr.json();if(gr.ok&&gd?.Customer){payload={...payload,Id:m.external_id,SyncToken:gd.Customer.SyncToken,sparse:true};}}
   const r=await fetch(`${api}/v3/company/${encodeURIComponent(realm)}/customer?minorversion=75`,{method:"POST",headers:{Authorization:`Bearer ${c.access_token}`,Accept:"application/json","Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok||!d?.Customer)throw new Error(d?.Fault?.Error?.[0]?.Message||"QuickBooks customer sync failed.");await saveMapping("quickbooks","customer",customerId,d.Customer.Id,d.Customer.SyncToken||null);await mark("quickbooks",{last_synced_at:now(),last_error:null,public_settings:{...(await integration("quickbooks"))?.public_settings,sync_available:true}});return json({ok:true,external_id:d.Customer.Id});
  }
  if(action==="xero.sync_contact"){
   if(!ownerManager)return json({error:"Only a shop owner or manager can sync accounting."},403);const c=await requireConnected("xero");const customerId=String(body.customer_id||"");const {data:cu}=await admin.from("customers").select("*").eq("shop_id",member.shop_id).eq("id",customerId).single();if(!cu)throw new Error("Customer not found.");const tenant=c.credential_metadata?.tenant_id;if(!tenant)throw new Error("Xero organization is missing.");const m=await mapping("xero","customer",customerId);const contact:any={Name:cu.name,EmailAddress:cu.email||undefined,Phones:cu.phone?[{PhoneType:"MOBILE",PhoneNumber:cu.phone}]:undefined,Addresses:cu.address?[{AddressType:"STREET",AddressLine1:cu.address}]:undefined};if(m?.external_id)contact.ContactID=m.external_id;const r=await fetch("https://api.xero.com/api.xro/2.0/Contacts",{method:"POST",headers:{Authorization:`Bearer ${c.access_token}`,"Xero-tenant-id":tenant,Accept:"application/json","Content-Type":"application/json"},body:JSON.stringify({Contacts:[contact]})});const d=await r.json();const out=d?.Contacts?.[0];if(!r.ok||!out?.ContactID)throw new Error(d?.Elements?.[0]?.ValidationErrors?.[0]?.Message||"Xero contact sync failed.");await saveMapping("xero","customer",customerId,out.ContactID,null);await mark("xero",{last_synced_at:now(),last_error:null,public_settings:{...(await integration("xero"))?.public_settings,sync_available:true}});return json({ok:true,external_id:out.ContactID});
  }
  return json({error:"Unknown integration action."},400);
 }catch(err){console.error(err);return json({error:err instanceof Error?err.message:"Integration action failed."},500);}
});