import { createClient } from "npm:@supabase/supabase-js@2.112.4";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
function envKey(jsonName:string,legacyName:string){try{const p=JSON.parse(Deno.env.get(jsonName)||"{}");if(p?.default)return p.default;}catch{}return Deno.env.get(legacyName)||"";}
const addSeconds=(s:number)=>new Date(Date.now()+Math.max(0,s)*1000).toISOString();
Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed"},405);
 const supabaseUrl=Deno.env.get("SUPABASE_URL")!;const anon=envKey("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY");const service=envKey("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");const auth=req.headers.get("Authorization")||"";
 const uc=createClient(supabaseUrl,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const admin=createClient(supabaseUrl,service,{auth:{persistSession:false}});const {data:{user}}=await uc.auth.getUser();if(!user)return json({error:"Authentication required."},401);
 const {data:member}=await admin.from("shop_members").select("shop_id,status").eq("user_id",user.id).eq("status","active").limit(1).maybeSingle();if(!member)return json({error:"Active shop membership required."},403);
 const body=await req.json().catch(()=>({}));if(String(body.action||"sync_job")!=="sync_job")return json({error:"Unknown action."},400);const jobId=String(body.job_id||"");if(!jobId)return json({error:"Job is required."},400);
 const {data:ints}=await admin.from("shop_integrations").select("provider,status").eq("shop_id",member.shop_id).in("provider",["google_calendar","microsoft_calendar"]);const status=Object.fromEntries((ints||[]).map((x:any)=>[x.provider,x.status]));const provider=status.google_calendar==="connected"?"google_calendar":status.microsoft_calendar==="connected"?"microsoft_calendar":null;if(!provider)return json({ok:true,skipped:true,reason:"No external calendar connected."});
 const {data:j,error:je}=await admin.from("jobs").select("*,customers(name),vehicles(year,make,model)").eq("shop_id",member.shop_id).eq("id",jobId).single();if(je||!j)return json({error:"Job not found."},404);if(!j.scheduled_start_at||!j.scheduled_end_at)return json({error:"Schedule the job first."},409);
 let {data:c}=await admin.from("shop_integration_credentials").select("*").eq("shop_id",member.shop_id).eq("provider",provider).maybeSingle();if(!c?.access_token)return json({error:"Calendar credentials are missing. Reconnect the calendar."},409);
 const exp=c.token_expires_at?new Date(c.token_expires_at).getTime():0;
 if(exp&&exp<Date.now()+120000&&c.refresh_token){
  if(provider==="google_calendar"){
   const id=Deno.env.get("GOOGLE_CLIENT_ID")||"",secret=Deno.env.get("GOOGLE_CLIENT_SECRET")||"";const f=new URLSearchParams({client_id:id,client_secret:secret,refresh_token:c.refresh_token,grant_type:"refresh_token"});const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:f});const t=await r.json();if(!r.ok||!t.access_token)return json({error:"Google Calendar needs to be reconnected."},409);c={...c,access_token:t.access_token,token_expires_at:addSeconds(Number(t.expires_in||3600))};
  }else{
   const id=Deno.env.get("MICROSOFT_CLIENT_ID")||"",secret=Deno.env.get("MICROSOFT_CLIENT_SECRET")||"",tenant=Deno.env.get("MICROSOFT_TENANT_ID")||"common";const f=new URLSearchParams({client_id:id,client_secret:secret,refresh_token:c.refresh_token,grant_type:"refresh_token"});const r=await fetch(`https://login.microsoftonline.com/${encodeURIComponent(tenant)}/oauth2/v2.0/token`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:f});const t=await r.json();if(!r.ok||!t.access_token)return json({error:"Outlook Calendar needs to be reconnected."},409);c={...c,access_token:t.access_token,refresh_token:t.refresh_token||c.refresh_token,token_expires_at:addSeconds(Number(t.expires_in||3600))};
  }
  await admin.from("shop_integration_credentials").upsert({...c,shop_id:member.shop_id,provider,updated_at:new Date().toISOString()},{onConflict:"shop_id,provider"});
 }
 const vehicle=[j.vehicles?.year,j.vehicles?.make,j.vehicles?.model].filter(Boolean).join(" ");const title=`${j.customers?.name||"Customer"} - ${vehicle||"Service Job"}`;const description=[j.customer_states,j.schedule_notes].filter(Boolean).join("\n\n");
 const {data:m}=await admin.from("integration_entity_mappings").select("*").eq("shop_id",member.shop_id).eq("provider",provider).eq("entity_type","job").eq("local_id",jobId).limit(1).maybeSingle();
 let externalId=m?.external_id||null,link=null;
 if(provider==="google_calendar"){
  const event={summary:title,description,start:{dateTime:j.scheduled_start_at},end:{dateTime:j.scheduled_end_at},location:j.current_location?.raw||undefined};
  let url=externalId?`https://www.googleapis.com/calendar/v3/calendars/primary/events/${encodeURIComponent(externalId)}`:"https://www.googleapis.com/calendar/v3/calendars/primary/events";let method=externalId?"PATCH":"POST";let r=await fetch(url,{method,headers:{Authorization:`Bearer ${c.access_token}`,"Content-Type":"application/json"},body:JSON.stringify(event)});
  if(r.status===404&&externalId){externalId=null;r=await fetch("https://www.googleapis.com/calendar/v3/calendars/primary/events",{method:"POST",headers:{Authorization:`Bearer ${c.access_token}`,"Content-Type":"application/json"},body:JSON.stringify(event)});}const d=await r.json();if(!r.ok)return json({error:d?.error?.message||"Google Calendar sync failed."},r.status);externalId=d.id;link=d.htmlLink||null;
 }else{
  const iso=(v:string)=>String(v).replace(/Z$/,"");const event={subject:title,body:{contentType:"Text",content:description},start:{dateTime:iso(j.scheduled_start_at),timeZone:"UTC"},end:{dateTime:iso(j.scheduled_end_at),timeZone:"UTC"},location:{displayName:j.current_location?.raw||""}};
  let url=externalId?`https://graph.microsoft.com/v1.0/me/events/${encodeURIComponent(externalId)}`:"https://graph.microsoft.com/v1.0/me/events";let method=externalId?"PATCH":"POST";let r=await fetch(url,{method,headers:{Authorization:`Bearer ${c.access_token}`,"Content-Type":"application/json"},body:JSON.stringify(event)});
  if(r.status===404&&externalId){externalId=null;r=await fetch("https://graph.microsoft.com/v1.0/me/events",{method:"POST",headers:{Authorization:`Bearer ${c.access_token}`,"Content-Type":"application/json"},body:JSON.stringify(event)});}const text=await r.text();const d=text?JSON.parse(text):{};if(!r.ok)return json({error:d?.error?.message||"Outlook Calendar sync failed."},r.status);externalId=d.id||externalId;link=d.webLink||null;
 }
 if(!externalId)return json({error:"Calendar did not return an event ID."},502);const metadata=provider==="google_calendar"?{htmlLink:link}:{webLink:link};if(m)await admin.from("integration_entity_mappings").update({external_id:externalId,metadata,last_synced_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",m.id);else await admin.from("integration_entity_mappings").insert({shop_id:member.shop_id,provider,entity_type:"job",local_id:jobId,external_id:externalId,metadata,last_synced_at:new Date().toISOString()});await admin.from("shop_integrations").update({last_synced_at:new Date().toISOString(),last_error:null,updated_at:new Date().toISOString()}).eq("shop_id",member.shop_id).eq("provider",provider);return json({ok:true,provider,event_id:externalId,link,updated:!!m});
});