import { createClient } from "npm:@supabase/supabase-js@2.112.4";

const cors={"Access-Control-Allow-Origin":"https://mobile-mechanic.app","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
function envKey(jsonName:string,legacyName:string){try{const p=JSON.parse(Deno.env.get(jsonName)||"{}");if(p?.default)return p.default;}catch{}return Deno.env.get(legacyName)||"";}
function outputText(data:any){if(typeof data?.output_text==="string"&&data.output_text.trim())return data.output_text.trim();const out:string[]=[];for(const item of data?.output||[])for(const c of item?.content||[])if(c?.type==="output_text"&&c?.text)out.push(c.text);return out.join("\n").trim();}
const safe=(v:unknown,max=800)=>String(v??"").slice(0,max);
async function creditState(admin:any,shopId:string,trialExpiresAt:any){const {data,error}=await admin.from("ai_credit_transactions").select("amount_cents,credit_bucket").eq("shop_id",shopId);if(error)throw error;let promotional=0,purchased=0;for(const r of data||[]){const n=Number(r.amount_cents||0);if(r.credit_bucket==="promotional")promotional+=n;else purchased+=n;}const end=trialExpiresAt?new Date(trialExpiresAt).getTime():0;const trialActive=Boolean(end&&Date.now()<end);if(!trialActive)promotional=0;return {promotional:Math.max(0,promotional),purchased,total:Math.max(0,promotional)+purchased};}
async function meterAI(admin:any,args:{shopId:string,feature:string,model:string,response:any,trialExpiresAt:any,metadata?:any}){const responseId=String(args.response?.id||"");if(!responseId)return 0;const {data:existing}=await admin.from("ai_usage_ledger").select("id,billable_cost_cents").eq("openai_response_id",responseId).maybeSingle();if(existing)return Number(existing.billable_cost_cents||0);const {data:rate,error:rateError}=await admin.from("ai_model_rates").select("input_per_million,cached_input_per_million,output_per_million").eq("model",args.model).eq("active",true).maybeSingle();if(rateError||!rate)throw rateError||new Error(`AI rate not configured for ${args.model}.`);const u=args.response?.usage||{},input=Number(u.input_tokens||0),cached=Math.min(input,Number(u.input_tokens_details?.cached_tokens||0)),output=Number(u.output_tokens||0),nonCached=Math.max(0,input-cached);const cents=Number((((nonCached*Number(rate.input_per_million)+cached*Number(rate.cached_input_per_million)+output*Number(rate.output_per_million))/1_000_000)*100).toFixed(6));const state=await creditState(admin,args.shopId,args.trialExpiresAt);const promoDebit=Math.min(Math.max(0,cents),state.promotional),purchasedDebit=Math.max(0,cents-promoDebit);if(promoDebit>0){const {error}=await admin.from("ai_credit_transactions").insert({shop_id:args.shopId,kind:"usage",amount_cents:-promoDebit,source:args.feature,reference_id:`ai_usage:${responseId}:promo`,credit_bucket:"promotional",metadata:{model:args.model,...(args.metadata||{})}});if(error&&error.code!=="23505")throw error;}if(purchasedDebit>0){const {error}=await admin.from("ai_credit_transactions").insert({shop_id:args.shopId,kind:"usage",amount_cents:-purchasedDebit,source:args.feature,reference_id:`ai_usage:${responseId}:purchased`,credit_bucket:"purchased",metadata:{model:args.model,...(args.metadata||{})}});if(error&&error.code!=="23505")throw error;}const {error:ledgerError}=await admin.from("ai_usage_ledger").insert({shop_id:args.shopId,user_id:null,feature:args.feature,model:args.model,input_tokens:input,cached_input_tokens:cached,output_tokens:output,provider_cost_cents:cents,billable_cost_cents:cents,openai_response_id:responseId,metadata:args.metadata||{}});if(ledgerError&&ledgerError.code!=="23505")throw ledgerError;return cents;}

Deno.serve(async(req)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
  if(req.method!=="POST")return json({error:"Method not allowed"},405);
  const supabaseUrl=Deno.env.get("SUPABASE_URL")!;const service=envKey("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");const admin=createClient(supabaseUrl,service,{auth:{persistSession:false}});let intakeId="";
  try{
    const {data:expected,error:secretError}=await admin.rpc("get_intake_internal_secret");
    const supplied=req.headers.get("x-intake-internal-token")||"";
    const internalAuthorized=!secretError&&Boolean(expected)&&supplied===expected;
    const body=await req.json().catch(()=>({}));intakeId=String(body.intake_id||"");if(!/^[0-9a-f-]{36}$/i.test(intakeId))return json({error:"Invalid intake id"},400);
    const {data:intake,error:intakeError}=await admin.from("intake_submissions").select("id,shop_id,vehicle,customer_states,ai_status,ai_workup,updated_at").eq("id",intakeId).maybeSingle();if(intakeError)throw intakeError;if(!intake)return json({ok:true,status:"not_found"});
    if(!internalAuthorized){
      const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");
      const {data:{user}}=await admin.auth.getUser(token);
      if(!user)return json({error:"Forbidden"},403);
      const {data:member}=await admin.from("shop_members").select("shop_id").eq("shop_id",intake.shop_id).eq("user_id",user.id).eq("status","active").maybeSingle();
      if(!member)return json({error:"Forbidden"},403);
    }
    if(intake.ai_status==="complete"&&intake.ai_workup)return json({ok:true,status:"complete"});
    const {data:claimed,error:claimError}=await admin.from("intake_submissions").update({ai_status:"processing",ai_error:null,updated_at:new Date().toISOString()}).eq("id",intakeId).in("ai_status",["pending","error"]).select("id").maybeSingle();if(claimError)throw claimError;if(!claimed)return json({ok:true,status:"already_processing"});
    const {data:shop}=await admin.from("shops").select("trial_expires_at,labor_rate,tax_rate,parts_markup,travel_fee").eq("shop_id",intake.shop_id).single();
    const wallet=await creditState(admin,intake.shop_id,shop?.trial_expires_at);if(wallet.total<=0)throw new Error("ai_balance_empty: AI balance is empty. Add AI Balance in Billing to keep automatic intake analysis running.");
    const openaiKey=Deno.env.get("OPENAI_API_KEY")||"";if(!openaiKey)throw new Error("openai_needs_key: OpenAI API key is not configured for automatic intake analysis.");
    const vehicle=intake.vehicle||{};const context={vehicle:{year:vehicle.year||null,make:vehicle.make||null,model:vehicle.model||null,submodel:vehicle.submodel||null,engine:vehicle.engine||null,drivetrain:vehicle.drivetrain||null,mileage:vehicle.mileage||null,vin:vehicle.vin||null},customer_concern:safe(intake.customer_states,5000),shop_pricing:{labor_rate:Number(shop?.labor_rate||75),parts_markup_percent:Number(shop?.parts_markup||0),tax_rate_percent:Number(shop?.tax_rate||0),travel_fee:Number(shop?.travel_fee||0)}};
    const schema={type:"object",additionalProperties:false,properties:{summary:{type:"string"},likely_causes:{type:"array",items:{type:"object",additionalProperties:false,properties:{cause:{type:"string"},likelihood:{type:"string",enum:["higher","possible","lower"]},why:{type:"string"}},required:["cause","likelihood","why"]}},first_checks:{type:"array",items:{type:"string"}},diagnostic_tests:{type:"array",items:{type:"object",additionalProperties:false,properties:{test:{type:"string"},what_to_watch:{type:"string"},meaning:{type:"string"}},required:["test","what_to_watch","meaning"]}},do_not_overlook:{type:"array",items:{type:"string"}},systems_to_inspect:{type:"array",items:{type:"string"}},safety:{type:"object",additionalProperties:false,properties:{level:{type:"string",enum:["normal","caution","urgent"]},note:{type:"string"}},required:["level","note"]},mechanic_note:{type:"string"},quote_draft:{type:"object",additionalProperties:false,properties:{warning:{type:"string"},good:{type:"object",additionalProperties:false,properties:{title:{type:"string"},summary:{type:"string"},labor_hours:{type:"number"},parts_cost:{type:"number"}},required:["title","summary","labor_hours","parts_cost"]},better:{type:"object",additionalProperties:false,properties:{title:{type:"string"},summary:{type:"string"},labor_hours:{type:"number"},parts_cost:{type:"number"}},required:["title","summary","labor_hours","parts_cost"]},best:{type:"object",additionalProperties:false,properties:{title:{type:"string"},summary:{type:"string"},labor_hours:{type:"number"},parts_cost:{type:"number"}},required:["title","summary","labor_hours","parts_cost"]}},required:["warning","good","better","best"]}},required:["summary","likely_causes","first_checks","diagnostic_tests","do_not_overlook","systems_to_inspect","safety","mechanic_note","quote_draft"]};
    const instructions=`You are Mobile Mechanic AI performing a PRELIMINARY mechanic-facing diagnostic workup from customer intake only. Use the vehicle information and the customer's own complaint. Do not claim a diagnosis is confirmed. Rank plausible causes qualitatively, explain why each fits, list fast first checks, and give concrete confirmation tests a trained mechanic can perform. Call out common overlooked causes and meaningful safety concerns. If the complaint is vague or evidence is insufficient, say that clearly and make the first checks diagnostic rather than guessing. Do not invent trouble codes, measurements, part numbers, service specifications, recalls, warranties, or inspection findings that were not provided. Create a Good/Better/Best quote draft automatically using the supplied shop pricing. Because intake facts are unverified, Good should normally cover diagnostic/inspection work, while Better and Best may show clearly labeled likely-repair ranges only when supported by the complaint. Never claim the price or diagnosis is final. Keep it concise and useful to a working automotive technician.`;
    const model="gpt-5.6-sol";
    const resp=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${openaiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model,reasoning:{effort:"medium"},instructions,input:`CUSTOMER INTAKE\n${JSON.stringify(context,null,2)}\n\nCreate the preliminary diagnostic workup.`,text:{format:{type:"json_schema",name:"intake_diagnostic_workup",strict:true,schema}}})});
    const data=await resp.json().catch(()=>({}));if(!resp.ok){const e=data?.error||{};const code=e?.code||e?.type||`http_${resp.status}`;throw new Error(`${code}: ${e?.message||`AI workup request failed (${resp.status}).`}`);}
    const aiCostCents=await meterAI(admin,{shopId:intake.shop_id,feature:"intake_ai_workup",model,response:data,trialExpiresAt:shop?.trial_expires_at,metadata:{intake_id:intakeId}});
    const text=outputText(data);if(!text)throw new Error("AI workup response was empty.");let workup:any;try{workup=JSON.parse(text);}catch{throw new Error("AI workup response was not valid JSON.");}
    const pricing=context.shop_pricing;const round=(n:any)=>Math.round(Math.max(0,Number(n||0))*100)/100;for(const key of ["good","better","best"]){const option=workup?.quote_draft?.[key];if(!option)continue;const hours=Math.min(100,Math.max(0,Number(option.labor_hours||0)));const parts=round(option.parts_cost);const marked=parts*(1+Math.min(300,Math.max(0,pricing.parts_markup_percent))/100);const subtotal=hours*pricing.labor_rate+marked+pricing.travel_fee;const total=round(subtotal+subtotal*Math.min(25,Math.max(0,pricing.tax_rate_percent))/100);option.price=total;option.breakdown={labor_hours:round(hours),labor:round(hours*pricing.labor_rate),parts_cost:parts,marked_parts:round(marked),travel:round(pricing.travel_fee),tax:round(total-subtotal)};}
    const {error:updateError}=await admin.from("intake_submissions").update({ai_workup:workup,ai_status:"complete",ai_error:null,updated_at:new Date().toISOString()}).eq("id",intakeId);if(updateError)throw updateError;
    await admin.from("feature_usage_events").insert({shop_id:intake.shop_id,feature:"intake_ai_workup",metadata:{intake_id:intakeId,model,ai_cost_cents:aiCostCents}});return json({ok:true,status:"complete",ai_cost_cents:aiCostCents});
  }catch(err){console.error(err);if(intakeId){try{await admin.from("intake_submissions").update({ai_status:"error",ai_error:safe(err instanceof Error?err.message:"AI workup failed",500),updated_at:new Date().toISOString()}).eq("id",intakeId);}catch{}}return json({error:err instanceof Error?err.message:"AI workup failed"},500);}
});
